int _putchar(char c);
void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int find_second(int n, int i);
int is_palindrome(char *s);
int find_palindrome(char *s, int start, int end);
int is_prime_number(int n);
int find_prime(int ,int );
int wildcmp(char *s1, char *s2);
int find_wildcmp(char *s1, char *s2, int);
